### ISSUE TITLE
Fix codecov badge

### ISSUE THREAD

**Issue by ewallace** [ropensci/tidyqpcr#187]
I updated the codecov badge in README.md (branch ropensci-accept) to point to the new repo address at https://github.com/ropensci/tidyqpcr/.

@DimmestP might you be able to fix that badge so it works again? Pointing to the main branch?

**Comment by ewallace** [comment]
Ok. Now a page exists: https://codecov.io/gh/ropensci/tidyqpcr/

And I have learned the function of codemeta.json and updated that automatically in commit a610fbd.

So I believe this to be fixed, and that as soon as there is a commit to `main` then code coverage will be checked.

**Comment by ewallace** [comment]
Help: To fix this we need an @ropensci owner to give codecov repository access to ropensci/tidyqpcr

@jeroen is this something you can do?
 
Link: https://github.com/apps/codecov/installations/167080

**Comment by maelle** [comment]
:wave: @ewallace!

Ouch, the clunkiness isn't fun, sorry that you experience that and congrats on the peer-review approval!

Here are my notes:
- codecov has access to all repositories. 
- I see it works for https://github.com/ropensci/qualtRics/ (first example I could think of)
- How do you use to update the covr score? I'd recommend using the workflow of https://github.com/r-lib/actions/tree/v2/examples, you can run `usethis::use_github_action("test-coverage")` to get the file, then commit and push it.

Happy to help further as needed.

**Comment by ewallace** [comment]
Thanks @maelle, this worked!

**Comment by mpadge** [comment]
@maelle What i did yesterday was to go to codedov where us admins can see a status view of all repos, and that clearly said this repo was just waiting for a push. So this whole process actually demonstrates that at least this piece of our infrastructure "just works" :relieved: - in other words, that codecov itself automatically and perfectly maps the repo transfer, including updating/re-mapping auth tokens. Nice.
