### ISSUE TITLE
Update authors in DESC?

### ISSUE THREAD

**Issue by mpadge** [ropensci/tidyqpcr#192]
@ewallace @DimmestP Your DESCRIPTION file currently has:
https://github.com/ropensci/tidyqpcr/blob/0dd9c97871259dfb96c0c788aa97ecec2dc46ede/DESCRIPTION#L5-L6
with Sam as "ctb". The review process seemed to indicate a co-author status; does that mean "ctb" should be changed to "aut"? I'm asking because this package is about to feature in our [monthly June newsletter](https://github.com/ropensci/roweb3/pull/351) (you can click on "deploy-preview" at the bottom to preview) and auto-lists only one author. Intended publication date is tomorrow (Fri 24th June). Any changes prior to that time will be automatically integrated, meaning if Sam is supposed to be listed as co-author, then putting "aut" in that line will be reflected in our newsletter. Thanks! (and ping @maelle)

**Comment by mpadge** [comment]
Thank you!

**Comment by maelle** [comment]
Registry updated https://github.com/ropensci/roregistry/commit/b8f905f56d87c18aca1c60aa030131c4680461a2 :tada:
