### ISSUE TITLE
Include as exported data sets the data from 10.1016/j.ymeth.2012.08.011

### ISSUE THREAD

**Issue by ramiromagno** [ropensci/tidyqpcr#198]
Hi @ewallace,

I would like to include data from [dx.doi.org/10.1016/j.ymeth.2012.08.011](http://dx.doi.org/10.1016/j.ymeth.2012.08.011) in `{tidyqpcr}`:

| File                   | Size |
| ---------------------- | ---- |
| Data_Vermeulen_A.xls   | 5.7M |
| Data_Vermeulen_B.xls   | 5.7M |
| Data_Vermeulen_C.xls   | 5.7M |
| Data_Vermeulen_D.xls   | 5.7M |
| technical_datasets.xls | 795K |

I think these data could be really useful for testing baseline subtraction and other processing methodologies.

Given that:

- I can see this data being used in many places in the package, including in the testing of functions
- That it takes up quite some space (albeit compression could help)

We could perhaps add it as raw data to `data-raw/`, and then include it as exported data sets (i.e. tibbles) that would be readily available for testing and examples. We could also make a companion data package, and make `{tidyqpcr}` depend on that...

**Comment by ramiromagno** [comment]
I just put together an R data package for the Vermeulen data: https://github.com/ramiromagno/vermeulen.

**Comment by ramiromagno** [comment]
This one might be useful too: https://github.com/ramiromagno/ruijter

**Comment by ramiromagno** [comment]
vermeulen is now on CRAN.

**Comment by ramiromagno** [comment]
`{ruijter}` is on its way to CRAN.

**Comment by ewallace** [comment]
Hi @ramiromagno I am just getting back to some maintenance updates on tidyqpcr after a long hiatus and silence. Are you still interested in helping to tie some of these into tidyqpcr?

**Comment by ramiromagno** [comment]
Hi @ewallace:

Yes! It's funny you're getting back at this now because I am right now finishing a set of R data packages that provide a bunch of qPCR data sets:

- https://github.com/ramiromagno/guescini
- https://github.com/ramiromagno/vermeulen
- https://github.com/ramiromagno/rutledge
- https://github.com/ramiromagno/batsch
- https://github.com/ramiromagno/ruijter
- https://github.com/ramiromagno/boggy
- https://github.com/ramiromagno/sisti
- https://github.com/ramiromagno/karlen (under CRAN submission)
- Planning on adding the data by Lievens et al. (2012) as a package sometime this week: https://academic.oup.com/nar/article/40/2/e10/2409569

**Comment by ewallace** [comment]
@ramiromagno that looks very cool, good to be back in touch.

It looks like your packages already do the pre-tidying of the data?

How were you thinking of fitting these together with tidyqpcr?

**Comment by ramiromagno** [comment]
I was thinking of using these datasets for testing tidyqpcr algorithms. So we could use these data package as dependencies, namely add them to Suggests (because we'd use them only in unit tests...?)?

**Comment by ramiromagno** [comment]
Hi @ewallace:

Originally, I planned to include a set of these data in tidyqpcr for testing purposes. However, I've since resolved this matter by integrating these datasets into separate R packages. Therefore, it's now feasible to rely on them if necessary. As a result, I will now close this issue.
