### ISSUE TITLE
User Interviews

### ISSUE THREAD

**Issue by DimmestP** [ropensci/tidyqpcr#65]
tidyqpcr is intended to be 
a) a user friendly and flexible tool for analysing qPCR data and 
b) an educational tool for users to learn how to conduct MIQE-compliant qPCR experiments and also
c) a friendly way to learn the basic building blocks of tidy data analysis. 

We are actively engaging with users to gain feedback on documentation and usability. If you are looking to help improve tidyqcr for everyone, or just interested to learn more, please volunteer to be interviewed. Add your name as a comment below, and we will be in touch!

**Comment by DimmestP** [comment]
Rosey Bayne 04-05-2020

Stick to consistent naming convention 
Excel is the common way to conduct qpcr analysis across research groups

**Comment by DimmestP** [comment]
David Barrass 18-15-2020

Standard error or standard deviation on graphs?
Multi-gene normalisation

**Comment by DimmestP** [comment]
Stuart McKeller 02-06-2020

Remove outlying replicates?
Cheat sheet of common functions could be helpful

**Comment by DimmestP** [comment]
Chris Katanski 11-09-2020

Printable plate plan which clearly states what each row/column should be filled with.
Option to integrate exactly what primers/probe sequences were used, what dye is used and experimental details.

**Comment by DimmestP** [comment]
Elliott Chapman 18-09-2020

Perhaps change the delta-cq example data so it aligns with MIQE-guidelines and tidy data.
Show/explain graph formatting code (currently hidden in vignettes) so people aren't confused why their graphs dont look like those in the vignette.

**Comment by ewallace** [comment]
@DimmestP will you update this ticket with the latest interview(s)?

**Comment by ewallace** [comment]
Closing as it's a long while since we did the user interviews.
